"""Standalone reasoning handler for a CoT-trained VnexAI model.
Generated by the cot_reasoning plugin. Requires: pip install llama-cpp-python

Usage:
    python reasoning_handler.py "your question here"
    python reasoning_handler.py "your question" --no-self-check
    python reasoning_handler.py "your question" --hide-think
"""
import sys
import argparse
from llama_cpp import Llama

MODEL_PATH = "model.gguf"
THINK_OPEN = "<think>"
THINK_CLOSE = "</think>"


def split_reasoning(raw_text):
    if THINK_CLOSE not in raw_text:
        return None, raw_text.strip()
    reasoning, _, answer = raw_text.partition(THINK_CLOSE)
    return reasoning.strip(), answer.strip()


def ask(llm, message, temperature, self_check, max_tokens):
    out1 = llm.create_completion(
        f"{message} {THINK_OPEN}", max_tokens=max_tokens,
        temperature=temperature, stop=["</s>"],
    )["choices"][0]["text"]
    reasoning1, answer1 = split_reasoning(THINK_OPEN + out1)

    if not self_check:
        return reasoning1, answer1

    prompt2 = (
        f"{message} {THINK_OPEN} {reasoning1 or ''} {THINK_CLOSE} "
        f"{answer1} Let me double check this. {THINK_OPEN}"
    )
    out2 = llm.create_completion(
        prompt2, max_tokens=max_tokens, temperature=temperature, stop=["</s>"],
    )["choices"][0]["text"]
    reasoning2, answer2 = split_reasoning(THINK_OPEN + out2)
    return (reasoning2 or reasoning1), (answer2 or answer1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("message")
    parser.add_argument("--no-self-check", action="store_true")
    parser.add_argument("--hide-think", action="store_true")
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--max-tokens", type=int, default=120)
    args = parser.parse_args()

    llm = Llama(model_path=MODEL_PATH, n_ctx=512, verbose=False)
    reasoning, answer = ask(
        llm, args.message, args.temperature,
        not args.no_self_check, args.max_tokens,
    )

    if reasoning and not args.hide_think:
        print("--- thinking ---")
        print(reasoning)
        print("--- answer ---")
    print(answer)


if __name__ == "__main__":
    main()
